version: '2'

services:

    docker_reverse_proxy:
        build:
            context: ./nginx
        volumes:
            - ./logs/nginx/:/var/log/nginx
        networks:
            - docker_reverse_proxy
        ports:
          - "80:80"
          - "443:443"

networks:
    docker_reverse_proxy:
        driver: "bridge"